import { contextBridge, ipcRenderer } from 'electron'

// `import type` is erased at build, so this shares main.ts's declaration
// without pulling its runtime into the sandboxed preload.
import type { Envelope } from './main'

async function invoke<T>(channel: string, ...args: unknown[]): Promise<T> {
  const res = (await ipcRenderer.invoke(`careerloom:${channel}`, ...args)) as Envelope<T>
  if (res.ok) return res.value
  // Reject with a plain object so `kind` survives the world boundary.
  return Promise.reject(res.error)
}

function subscribe<T>(channel: string, cb: (payload: T) => void): () => void {
  const listener = (_e: unknown, payload: T) => cb(payload)
  ipcRenderer.on(`careerloom:${channel}`, listener)
  return () => { ipcRenderer.removeListener(`careerloom:${channel}`, listener) }
}

// Shape matches CareerloomBridge (renderer/lib/types.ts), where it is typed.
const bridge = {
  getSettings: () => invoke('getSettings'),
  setRoot: (root: string) => invoke('setRoot', root),
  setRunner: (runner: string) => invoke('setRunner', runner),
  setApiKey: (key: string | null, provider?: string) => invoke('setApiKey', key, provider),
  setModel: (runner: string, model: string | null) => invoke('setModel', runner, model),
  listModels: (runner: string) => invoke('listModels', runner),
  chooseDirectory: () => invoke('chooseDirectory'),
  runnerStatus: () => invoke('runnerStatus'),
  modes: () => invoke('modes'),
  profileStatus: () => invoke('profileStatus'),
  getTracker: () => invoke('getTracker'),
  getPipeline: () => invoke('getPipeline'),
  listReports: () => invoke('listReports'),
  readReport: (rel: string) => invoke('readReport', rel),
  listRuns: () => invoke('listRuns'),
  getRunLog: (id: string) => invoke('getRunLog', id),
  deleteRuns: (ids: string[]) => invoke('deleteRuns', ids),
  startRun: (req: { mode: string; input?: string; skills?: string[] }) => invoke('startRun', req),
  evaluateJob: (input: string) => invoke('evaluateJob', input),
  cancelRun: (id: string) => invoke('cancelRun', id),
  setupCareerOps: (parent: string) => invoke('setupCareerOps', parent),
  prerequisites: () => invoke('prerequisites'),
  installCareerOpsDefault: () => invoke('installCareerOpsDefault'),
  onRun: (cb: (event: unknown) => void) => subscribe('run', cb),
  onSettings: (cb: () => void) => subscribe('settings', cb),
  bootstrapStatus: () => invoke('bootstrapStatus'),
  bootstrapStart: (arg?: { retry?: string }) => invoke('bootstrapStart', arg),
  onBootstrap: (cb: (status: unknown) => void) => subscribe('bootstrap', cb),
  getReadiness: (force?: boolean) => invoke('getReadiness', force),
  onReadiness: (cb: (event: unknown) => void) => subscribe('readiness', cb),
  // Resume
  resumeOverview: () => invoke('resumeOverview'),
  importResume: () => invoke('importResume'),
  parseResume: () => invoke('parseResume'),
  setTemplate: (name: string) => invoke('setTemplate', name),
  importTemplate: () => invoke('importTemplate'),
  createTemplate: (description: string) => invoke('createTemplate', description),
  previewTemplate: (name: string) => invoke('previewTemplate', name),
  exportResume: (format: string) => invoke('exportResume', format),
  revealExport: (file: string) => invoke('revealExport', file),
  readCv: () => invoke('readCv'),
  writeCv: (markdown: string) => invoke('writeCv', markdown),
  extractResume: (file: string) => invoke('extractResume', file),
  readProfile: () => invoke('readProfile'),
  researchProfile: () => invoke('researchProfile'),
  readResearch: () => invoke('readResearch'),
  renderTemplatePdf: (name: string) => invoke('renderTemplatePdf', name),
  savePdf: (name: string) => invoke('savePdf', name),
  // ————— ATS / Resume —————
  atsAnalyze: (input: unknown) => invoke('atsAnalyze', input),
  atsGet: (jobId?: string) => invoke('atsGet', jobId),
  atsAnswer: (runId: string, answers: unknown[], jobId?: string) => invoke('atsAnswer', runId, answers, jobId),
  atsPreviewApply: (findingId: string, answers?: unknown[]) => invoke('atsPreviewApply', findingId, answers),
  atsApply: (findingId: string, answers?: unknown[]) => invoke('atsApply', findingId, answers),
  atsUndo: (undoId: string) => invoke('atsUndo', undoId),
  atsDismiss: (findingId: string) => invoke('atsDismiss', findingId),
  atsHistory: () => invoke('atsHistory'),
  onAtsEvent: (cb: (event: unknown) => void) => subscribe('atsEvents', cb),
  // ————— Job page —————
  jobView: (id: string) => invoke('jobView', id),
  onJobView: (cb: (e: unknown) => void) => subscribe('jobView', cb),
  setHelperModel: (runner: string, model: string | null) => invoke('setHelperModel', runner, model),
  docsList: (jobId: string) => invoke('docsList', jobId),
  docsGenerate: (jobId: string, kind: string, options?: unknown) => invoke('docsGenerate', jobId, kind, options),
  docsReadText: (rel: string) => invoke('docsReadText', rel),
  docsReadPdf: (rel: string) => invoke('docsReadPdf', rel),
  docsReveal: (rel: string) => invoke('docsReveal', rel),
  docsSave: (rel: string) => invoke('docsSave', rel),
  onDocs: (cb: (e: unknown) => void) => subscribe('docs', cb),
  // Jobs
  listJobs: () => invoke('listJobs'),
  listPortals: () => invoke('listPortals'),
  scanPortals: (ids: string[]) => invoke('scanPortals', ids),
  countUnevaluated: (ids: string[]) => invoke('countUnevaluated', ids),
  deletePortals: (ids: string[], hideUnevaluated: boolean) => invoke('deletePortals', ids, hideUnevaluated),
  addDefaultPortals: () => invoke('addDefaultPortals'),
  switchToStarterPack: () => invoke('switchToStarterPack'),
  getPortal: (id: string) => invoke('getPortal', id),
  updatePortal: (id: string, patch: Record<string, unknown>) => invoke('updatePortal', id, patch),
  setPortalsEnabled: (ids: string[], enabled: boolean) => invoke('setPortalsEnabled', ids, enabled),
  listScans: () => invoke('listScans'),
  checkBoardUrl: (url: string) => invoke('checkBoardUrl', url),
  browserLoginStatus: () => invoke('browserLoginStatus'),
  prescreenStatus: () => invoke('prescreenStatus'),
  prescreenJobs: (ids?: string[]) => invoke('prescreenJobs', ids),
  readPrescreen: () => invoke('readPrescreen'),
  savePrescreenPolicy: (policy: unknown) => invoke('savePrescreenPolicy', policy),
  prescreenFeedback: (id: string, relevant: boolean | null) => invoke('prescreenFeedback', id, relevant),
  retrainPrescreen: () => invoke('retrainPrescreen'),
  localModelStatus: () => invoke('localModelStatus'),
  installLocalModel: () => invoke('installLocalModel'),
  evaluateJobs: (ids: string[], force?: boolean) => invoke('evaluateJobs', ids, force),
  setPortalGuideline: (id: string, text: string) => invoke('setPortalGuideline', id, text),
  improvePortalGuideline: (id: string, draft: string) => invoke('improvePortalGuideline', id, draft),
  // Agent chat
  listThreads: () => invoke('listThreads'),
  getThread: (id: string) => invoke('getThread', id),
  sendMessage: (threadId: string | null, text: string, opts?: unknown) => invoke('sendMessage', threadId, text, opts),
  attachmentData: (threadId: string, attachmentId: string) => invoke('attachmentData', threadId, attachmentId),
  renameThread: (id: string, title: string) => invoke('renameThread', id, title),
  deleteThread: (id: string) => invoke('deleteThread', id),
  continueRun: (runId: string) => invoke('continueRun', runId),
  // Monitoring
  getMetrics: (range?: { from: string; to: string } | null) => invoke('getMetrics', range),
  // Integrations
  listIntegrations: () => invoke('listIntegrations'),
  getIntegration: (id: string) => invoke('getIntegration', id),
  previewInstall: (url: string) => invoke('previewInstall', url),
  installIntegration: (url: string) => invoke('installIntegration', url),
  integrationAction: (id: string, action: string) => invoke('integrationAction', id, action),
  setIntegrationConfig: (id: string, patch: Record<string, unknown>) => invoke('setIntegrationConfig', id, patch),
  previewWebBoard: (urls: string[]) => invoke('previewWebBoard', urls),
  addWebBoard: (name: string, urls: string[], instructions: string, fetch?: 'firecrawl' | 'browser') => invoke('addWebBoard', name, urls, instructions, fetch),
  browserConsentNeeded: (ids: string[]) => invoke('browserConsentNeeded', ids),
  acknowledgeBrowser: (domains: string[]) => invoke('acknowledgeBrowser', domains),
  // ————— Settings rebuild —————
  keysList: () => invoke('keysList'),
  keysSet: (id: string, value: string | null) => invoke('keysSet', id, value),
  keysTest: (id: string) => invoke('keysTest', id),
  llmProviders: () => invoke('llmProviders'),
  llmSet: (patch: unknown) => invoke('llmSet', patch),
  llmModels: (provider: string) => invoke('llmModels', provider),
  prefsGet: () => invoke('prefsGet'),
  prefsSet: (patch: unknown) => invoke('prefsSet', patch),
  browserAcks: () => invoke('browserAcks'),
  browserRevoke: (domain: string) => invoke('browserRevoke', domain),
  dataLocations: () => invoke('dataLocations'),
  revealPath: (path: string) => invoke('revealPath', path),
  runLogTail: (id: string, lines?: number) => invoke('runLogTail', id, lines),
  dataStats: () => invoke('dataStats'),
  dataClear: (scope: string) => invoke('dataClear', scope),
  retentionPrune: () => invoke('retentionPrune'),
  settingsReset: (scope: string) => invoke('settingsReset', scope),
  diagnostics: () => invoke('diagnostics'),
  checkForUpdates: () => invoke('checkForUpdates'),
  // ————— Interview Copilot (plan §4) —————
  copilotGetConfig: (...a: unknown[]) => invoke('copilotGetConfig', ...a),
  copilotSetConfig: (...a: unknown[]) => invoke('copilotSetConfig', ...a),
  copilotReadiness: (...a: unknown[]) => invoke('copilotReadiness', ...a),
  copilotContextPreview: (...a: unknown[]) => invoke('copilotContextPreview', ...a),
  copilotProbeAudio: (...a: unknown[]) => invoke('copilotProbeAudio', ...a),
  copilotOpenSystemSettings: (...a: unknown[]) => invoke('copilotOpenSystemSettings', ...a),
  copilotStart: (...a: unknown[]) => invoke('copilotStart', ...a),
  copilotStop: (...a: unknown[]) => invoke('copilotStop', ...a),
  copilotAnswer: (...a: unknown[]) => invoke('copilotAnswer', ...a),
  copilotScreenshot: (...a: unknown[]) => invoke('copilotScreenshot', ...a),
  copilotOverlay: (...a: unknown[]) => invoke('copilotOverlay', ...a),
  copilotAckPrivacyNotice: (...a: unknown[]) => invoke('copilotAckPrivacyNotice', ...a),
  copilotListSessions: (...a: unknown[]) => invoke('copilotListSessions', ...a),
  copilotSessionsForJob: (...a: unknown[]) => invoke('copilotSessionsForJob', ...a),
  copilotGetSession: (...a: unknown[]) => invoke('copilotGetSession', ...a),
  copilotDeleteSession: (...a: unknown[]) => invoke('copilotDeleteSession', ...a),
  copilotExportConsents: (...a: unknown[]) => invoke('copilotExportConsents', ...a),
  copilotPracticeQuestions: (...a: unknown[]) => invoke('copilotPracticeQuestions', ...a),
  copilotListSttModels: (...a: unknown[]) => invoke('copilotListSttModels', ...a),
  copilotBenchmarkStt: (...a: unknown[]) => invoke('copilotBenchmarkStt', ...a),
  copilotInstallStt: (...a: unknown[]) => invoke('copilotInstallStt', ...a),
  copilotHfCheck: (...a: unknown[]) => invoke('copilotHfCheck', ...a),
  copilotRemoveStt: (...a: unknown[]) => invoke('copilotRemoveStt', ...a),
  copilotListLlmModels: (...a: unknown[]) => invoke('copilotListLlmModels', ...a),
  copilotTestLlmModel: (...a: unknown[]) => invoke('copilotTestLlmModel', ...a),
  copilotCheckHotkey: (...a: unknown[]) => invoke('copilotCheckHotkey', ...a),
  copilotApplyDebrief: (...a: unknown[]) => invoke('copilotApplyDebrief', ...a),
  onCopilotEvent: (event: string, cb: (payload: unknown) => void) => subscribe(event, cb),
  copilotAudio: (msg: unknown) => ipcRenderer.send('careerloom:copilotAudio', msg),
  // ————— Job knowledge base + AI interviewer (kb plan §4) —————
  kbSummary: (...a: unknown[]) => invoke('kbSummary', ...a),
  kbList: (...a: unknown[]) => invoke('kbList', ...a),
  kbItem: (...a: unknown[]) => invoke('kbItem', ...a),
  kbEstimate: (...a: unknown[]) => invoke('kbEstimate', ...a),
  kbResearchStart: (...a: unknown[]) => invoke('kbResearchStart', ...a),
  kbResearchStop: (...a: unknown[]) => invoke('kbResearchStop', ...a),
  kbItemUpdate: (...a: unknown[]) => invoke('kbItemUpdate', ...a),
  kbItemAdd: (...a: unknown[]) => invoke('kbItemAdd', ...a),
  kbItemRemove: (...a: unknown[]) => invoke('kbItemRemove', ...a),
  kbExport: (...a: unknown[]) => invoke('kbExport', ...a),
  kbImport: (...a: unknown[]) => invoke('kbImport', ...a),
  kbSearchKeyTest: (...a: unknown[]) => invoke('kbSearchKeyTest', ...a),
  kbOpenSource: (...a: unknown[]) => invoke('kbOpenSource', ...a),
  interviewConfig: (...a: unknown[]) => invoke('interviewConfig', ...a),
  interviewSetConfig: (...a: unknown[]) => invoke('interviewSetConfig', ...a),
  interviewVoices: (...a: unknown[]) => invoke('interviewVoices', ...a),
  interviewPreviewVoice: (...a: unknown[]) => invoke('interviewPreviewVoice', ...a),
  interviewInstallVoice: (...a: unknown[]) => invoke('interviewInstallVoice', ...a),
  interviewSkillSignal: (...a: unknown[]) => invoke('interviewSkillSignal', ...a),
  interviewKokoroStatus: (...a: unknown[]) => invoke('interviewKokoroStatus', ...a),
  interviewPlanPreview: (...a: unknown[]) => invoke('interviewPlanPreview', ...a),
  onKbEvent: (event: string, cb: (payload: unknown) => void) => subscribe(event, cb),
  onTtsAudio: (cb: (m: unknown) => void) => subscribe('ttsAudio', cb),
  kbTtsPlayback: (msg: unknown) => ipcRenderer.send('careerloom:ttsPlayback', msg), // WP5 listens in main (echo gate)
  // Agent Skills
  skillsList: () => invoke('skillsList'),
  skillsPick: (kind: string) => invoke('skillsPick', kind),
  skillsInspect: (source: unknown) => invoke('skillsInspect', source),
  skillsInstall: (source: unknown, opts?: unknown) => invoke('skillsInstall', source, opts),
  skillsSetEnabled: (id: string, enabled: boolean) => invoke('skillsSetEnabled', id, enabled),
  skillsRemove: (id: string) => invoke('skillsRemove', id),
  skillsUpdate: (id: string) => invoke('skillsUpdate', id),
  // Pipeline
  setStatus: (nums: number[], status: string) => invoke('setStatus', nums, status),
  getUpdateStatus: () => invoke('getUpdateStatus'),
  onUpdateStatus: (cb: (status: unknown) => void) => subscribe('update', cb),
  openExternal: (url: string) => ipcRenderer.invoke('open-external', url),
  platform: process.platform,
  arch: process.arch,
}

contextBridge.exposeInMainWorld('careerloom', bridge)
